services:
  webtop:
    # Use the Ubuntu Webtop image with the MATE desktop environment
    image: lscr.io/linuxserver/webtop:ubuntu-mate	
    # The name of the container
    container_name: webtop
    environment:
      # PUID and PGID are the user and group IDs of the user running the container
      # These help with file permissions
      # You can find these by running `id` in the terminal or by running `id -u` and `id -g`
      - PUID=1000
      - PGID=1000
      # TZ is the timezone 
      - TZ=Etc/UTC
      # TITLE (optional) is the title of the web interface
      - TITLE=Webtop
      # Set HTTP authentication (optional)
      - CUSTOM_USER=user
      - CUSTOM_PASS=password   
    volumes:
      # Mount /config (set as the home directory) to the `home` in the current directory 
      - ./home:/config
      # Optionally, allow for Docker in Docker by sharing the Docker socket
      # The Webtop image has the Docker binary. If you're running an image that doesn't, install Docker in the container first.
      - /var/run/docker.sock:/var/run/docker.sock 
    ports:
      # Port 3000 is the web interface (kasmVNC)
      # Port 3001 is the  web interface (kasmVNC) with HTTPS
      - 3000:3000
      - 3001:3001
    # devices:
      # This optional mount should help with hardware acceleration (host should be Linux)
      # - /dev/dri:/dev/dri
    # The README mentions that this helps prevent web browsers from crashing
    shm_size: "1gb"
    # Restart the container unless stopped manually
    restart: unless-stopped
