version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - pass1=Ye
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: redis:alpine
    ports:
      - "6379:6379"
